
ifdef CONFIG_X64
CROSS_COMPILE_PREFIX = x86_64-kanawha-
endif
ifdef CONFIG_RISCV64
CROSS_COMPILE_PREFIX = riscv64-kanawha-
endif

CC := $(CROSS_COMPILE_PREFIX)gcc
CPP := $(CROSS_COMPILE_PREFIX)cpp
LD := $(CROSS_COMPILE_PREFIX)ld
AS := $(CROSS_COMPILE_PREFIX)gcc
AR := $(CROSS_COMPILE_PREFIX)ar

OBJCOPY := $(CROSS_COMPILE_PREFIX)objcopy
OBJDUMP := $(CROSS_COMPILE_PREFIX)objdump

